---
resources:
- name: resource-web-app-blue-green
  type: git
  source:
    uri: https://github.com/JellevdK/rws_concourse_blue_green.git

- name: resource-deploy-web-app-blue-green
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    skip_cert_check: true
jobs:
- name: job-deploy-app-blue-green
  serial: true
  plan:
  - get: resource-web-app-blue-green
    trigger: true
  - put: resource-deploy-web-app-blue-green
    params:
      manifest: resource-web-app-blue-green/webapp-blue-green/manifest.yml
      path: resource-web-app-blue-green/webapp-blue-green
